languageCode = "en-us"
title = "Developer Docs Blog"
theme = "Developer-Docs-Theme"
baseURL = "/"
relativeURLs = false

[params]
    custom_css = [
      "/css/developer_docs_style.css",
      "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    ]
    maxBlogPosts   = 10

[menu]
  [[menu.main]]
      identifier = "developer-home"
      name = "Developer Home"
      url = "/developer-home"
      weight = 1
  [[menu.main]]
      identifier = "developer-documentation"
      name = "Developer Documentation"
      url = "/developer-documentation"
      weight = 2
  [[menu.main]]
      identifier = "blogs"
      name = "Blogs"
      url = "/blogs"
      weight = 3
      [[menu.main]]
          identifier = "technical-blog"
          name = "Technical Blog"
          url = "/blogs/technical-blog"
          weight = 1
          parent="blogs"
      [[menu.main]]
          identifier = "rackspace-blog"
          name = "Rackspace Blog"
          url = "/blogs/rackspace-blog"
          weight = 2
          parent="blogs"
      [[menu.main]]
          identifier = "solve"
          name = "Solve: Thought Leadership"
          url = "/blogs/solve"
          weight = 3
          parent="blogs"
  [[menu.main]]
      identifier = "support-documentation"
      name = "Support Documentation"
      url = "/support-documentation"
      weight = 4
