:toc: macro
:toc-title:

= Rackspace Developer Docs Blog

toc::[]


The website is written in link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc], generated using link:https://gohugo.io/[Hugo], and hosted on GitHub.

== Requirements

In order to locally run you will need to either install Hugo and AsciiDoctor locally or run a docker image that contains Hugo and AsciiDoctor.

=== Install and Run Hugo and AsciiDoctor Locally

If you want to locally install the required tools, you first must have link://https://gohugo.io/[Hugo] installed and the `hugo` command available on your PATH. It is likely you can easily install `hugo` using your system's package manager. For more information about how to install Hugo please see its link:https://gohugo.io/getting-started/installing/[installation documentation].

Asciidoctor is also required to run. The `make install` command will install Asciidoctor using link:https://rubygems.org[Ruby Gem] and Bundler. You will need to have the `gem` command on your path. Please see the link:https://rubygems.org/pages/download[Ruby Gem installation docs] for more information.

It is recommended to install and run at least **Hugo 0.48**

=== Install and Run Hugo and AsciiDoctor via Docker

If you do not want to install a local copy of Hugo and AsciiDoctor, you can run a Hugo+AsciiDoctor docker image instead. You need to first create the docker image via `make hugo-docker`. Once you have a docker image, you can run the Hugo server via `make hugo-serve`.

== Installing

If you want to install and run Hugo and AsciiDoctor locally, the following command needs to be run in order to install a few dependencies:

[source, bash]
----
make install
----

==  Start local server

Hugo has a live `serve` command that runs a small, lightweight web server on your computer so you can test your site locally without needing to upload it anywhere.  As you make changes to files in your project, it will rebuild your project and reload the browser for you.

[source,bash]
----
make serve
----

If you did not install Hugo and AsciiDoctor locally, but you instead want to run with the docker image, you can use the hugo-serve make target instead:

[source,bash]
----
make hugo-serve
----

If everything is working as expected you should see something like the following being outputted:


You should now be able to access hugo running at link:http://localhost:1313/[http://localhost:1313]

This running instance should support live reload. Changes you make to files should be automatically updated in your running instance.

Some files may not be supported for live reload. If you are not automatically seeing your changes live you may need to restart the server. You can restart the server by pressing 'ctrl-c' and running `make serve` again (or `make hugo-serve` if you are running the docker image).

